%OPERACIÓNES MATEMATICAS BASICAS
%SUMA +
%RESTA -
%MULTIPLICACIÓN *
%MULTIPLICACIÓN (PUNTO) .*
%DIVISIÓN /
%DIVISIÓN (PUNTO) ./
%DIVISIÓN INVERTIDA \
%DIVISIÓN INVERTIDA (PUNTO) .\
%POTENCIA ^
%POTENCIA (PUNTO) .^
%FACTORIAL factorial()
%REDONDEO round()
%REDONDEO (CERO) fix()
%REDONDEO (-INFINITO) floor()
%REDONDEO (+INFINITO)
clc;
clear all;